### ISSUE TITLE
我有两个问题请教一下 (I've two questions to ask)

### ISSUE THREAD

**Issue by Guidozijef** [Halfeld/v-notes#5]
一、如何实现在编辑文本的时候使用MarkDown语法？
二、数据是存储在什么地方的？能不能直接存储在github或者一写云平台上面？

**Comment by Guidozijef** [comment]
为啥我下载后在本地运行起来，后来我启动其他项目，打开也是你这个记事本的项目，明明已经关了呀

**Comment by IgorHalfeld** [comment]
Hmm.. can you typing in english please?

**Comment by IgorHalfeld** [comment]
Google Translator Helping the humans haha

![image](https://user-images.githubusercontent.com/9022134/48863579-fa0d4200-edb0-11e8-9912-27c572fa6be3.png)

- I use the [marked](https://www.npmjs.com/package/marked) lib to make the parser.
- I use [LocalStorage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to persist data on your browser
- No. It's under [GPLv3 license](http://gplv3.fsf.org/)
